Update NewStart

diff --git a/NewStart b/NewStart
--- a/NewStart
+++ b/NewStart
@@ -37,6 +37,24 @@ fi
 echo ""
 echo ""
 echo "##########################################################"
+echo "Installing the 'reboot' file to '/usr/local/bin'"
+chmod +x uit
+sleep 2
+# Now we can copy the file using the 'REBOOT' command
+echo "Now we can copy the file using the 'UIT' command"
+sleep 2
+cp reboot /usr/local/bin
+echo "Checking if the copy was successful"
+sleep 3
+# Check if the copy was successful
+if [ $? -eq 0 ]; then
+  echo "File reboot successfully copied"
+else
+  echo "Error copying file"
+fi
+echo ""
+echo ""
+echo "##########################################################"
 echo "Start install"
 sleep 2
 echo ""
